// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestWithASPNET.Model.Context;

#nullable disable

namespace RestWithASPNET.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230313105744_SeedPersonAndBook")]
    partial class SeedPersonAndBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestWithASPNET.Model.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("longtext")
                        .HasColumnName("author");

                    b.Property<DateTime>("Launch_Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("launch_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Aghata Christie",
                            Launch_Date = new DateTime(1931, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 85.99m,
                            Title = "O caso dos dez negrinhos"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Aghata Christie",
                            Launch_Date = new DateTime(1946, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 77.50m,
                            Title = "O assassinato no expresso do oriente"
                        },
                        new
                        {
                            Id = 3L,
                            Author = "José de Alencar",
                            Launch_Date = new DateTime(1977, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 54.00m,
                            Title = "O guarani"
                        },
                        new
                        {
                            Id = 4L,
                            Author = "Julio Verne",
                            Launch_Date = new DateTime(1880, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 60.99m,
                            Title = "A volta ao mundo em 80 dias"
                        },
                        new
                        {
                            Id = 5L,
                            Author = "Julio Verne",
                            Launch_Date = new DateTime(1976, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75.00m,
                            Title = "Vinte léguas submarinas"
                        });
                });

            modelBuilder.Entity("RestWithASPNET.Model.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("person");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Rua José de Matos, 79 - Jdim Vale Verde - B Campos SP",
                            FirstName = "Cristiano",
                            Gender = "Male",
                            LastName = "Ap Lázaro"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Rua José de Matos, 79 - Jdim Vale Verde - B Campos SP",
                            FirstName = "Elenice",
                            Gender = "Female",
                            LastName = "C Lázaro"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Rua José de Matos, 79 - Jdim Vale Verde - B Campos SP",
                            FirstName = "Cristiane",
                            Gender = "Female",
                            LastName = "C Lázaro"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Rua José de Matos, 79 - Jdim Vale Verde - B Campos SP",
                            FirstName = "Bruno",
                            Gender = "Male",
                            LastName = "C Lázaro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
